import FWCore.ParameterSet.Config as cms

pfMassDecorrelatedInclParticleTransformerV1DiscriminatorsJetTags = cms.EDProducer(
   'BTagProbabilityToDiscriminator',
   discriminators = cms.VPSet(
      cms.PSet(
         name = cms.string('HbbvsQCD'),
         numerator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHbb'),
            ),
         denominator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHbb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDbb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDcc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDothers'),
            ),
         ),
      cms.PSet(
         name = cms.string('HccvsQCD'),
         numerator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHcc'),
            ),
         denominator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHcc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDbb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDcc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDothers'),
            ),
         ),
      cms.PSet(
         name = cms.string('HWW4qvsQCD'),
         numerator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq2c'),
            ),
         denominator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq2c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDbb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDcc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDothers'),
            ),
         ),
      cms.PSet(
         name = cms.string('HWW4q3qvsQCD'),
         numerator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq2c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq2c'),
            ),
         denominator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq2c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq2c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDbb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDcc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDothers'),
            ),
         ),
      cms.PSet(
         name = cms.string('HWWlvqqvsTopblv'),
         numerator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWev0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWev1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWmv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWmv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauev0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauev1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtaumv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtaumv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauhv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauhv1c'),
            ),
         denominator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWev0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWev1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWmv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWmv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauev0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauev1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtaumv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtaumv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauhv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauhv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWev'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWmv'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWtauhv'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWtauev'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWtaumv'),
            ),
         ),
      cms.PSet(
         name = cms.string('HWWlvqqvsQCDTop'),
         numerator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq2c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq2c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWev0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWev1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWmv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWmv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauev0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauev1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtaumv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtaumv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauhv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauhv1c'),
            ),
         denominator = cms.VInputTag(
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWqq2c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWq2c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWev0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWev1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWmv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWmv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauev0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauev1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtaumv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtaumv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauhv0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probHWqqWtauhv1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDbb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDcc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDb'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDc'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probQCDothers'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWqq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWqq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWq0c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWq1c'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWev'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWmv'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWtauhv'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWtauev'),
            cms.InputTag('pfMassDecorrelatedInclParticleTransformerV1JetTags', 'probTopbWtaumv'),
            ),
         ),
      )
   )
